from .funcs import function_1
from .funcs import function_2
from .funcs import function_3
from .funcs import exhaustive_search
from .funcs import dichotomy_method
from .funcs import golden_section
from .funcs import get_signal
from .funcs import linear_approx
from .funcs import rational_approx
from .funcs import least_squares
from .funcs import exhaustive_search_2d
from .funcs import gauss_method
from .funcs import nelder_mead
